### ISSUE TITLE
Your tip link doesn't work from BLW

### ISSUE THREAD

**Issue by Perlover** [Fittiboy/bitcoin-on-twitch#9] opened 2021-06-24 11:03 UTC
Hi,

I tried to [send tip](https://fitti.io/tips) from the BLW wallet (@btcontract - author of the LNURL) but I got the error:

"requirement failed: Action domain mismatch"

From the Blixt wallet - there is everything OK.

I think your chain URLs from LNURL communication has different domains but the [LNURL protocol requires](https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-pay.md) to have the same domains (#6 point - "url domain must be the same as `callback` domain at step 3" in example comment)

Is it your the bug or the BLW?

**Comment by Fittiboy** [comment] 2021-06-24 12:19
That's very interesting, thanks for pointing it out!
The issue is likely the fact that it violates the exact point you mentioned, as the `successAction` domain differs from the `callback` domain. I have changed the `successAction` url so that it is the same domain (it's not https://fitti.io/live/about, which redirects to the same page either way) as the callback, so it should work now.
I will keep this in mind for the future, and might open an issue in the LNbits repo to make the LNURLp extension enforce this part of the spec.
I will close this for now, but please feel free to reopen it if this didn't fix it!

**Closed as completed by Fittiboy** 2021-06-24 12:19 UTC

**Comment by Perlover** [comment] 2021-06-24 12:59
Hi!

Right now I tested it (from the BLW) - it works now how expected!

Best regards!

**Comment by Fittiboy** [comment] 2021-06-24 13:00
Thanks for committing some of your sats to confirming this, as I personally don't have BLW! :+1:
